version: '2'
services:
  default:
    links:
      - nuget:nuget
  nuget:
    image: ${KUDU_DOCKER_IMAGE_URL}
    volumes:
      - ${DOJO_WORK_OUTER}/e2e/baget-compat/data/:/data/
      - ${DOJO_WORK_OUTER}/e2e/baget-compat/cache/:/cache/
      - ${DOJO_WORK_OUTER}/e2e/input:/data/simple #simulates old LiGet's storage
    mem_limit: 550m
