version: '2'
services:
  default:
    links:
      - liget:nuget
  liget:
    image: ${KUDU_DOCKER_IMAGE_URL}
    volumes:
      - ${DOJO_WORK_OUTER}/e2e/liget0-compat/data/:/data
      - ${DOJO_WORK_OUTER}/e2e/liget0-compat/cache/:/cache
    mem_limit: 550m
