version: '2'
services:
  default:
    links:
      - liget:liget
  liget:
    image: ${KUDU_DOCKER_IMAGE_URL}
    volumes:
      - ${DOJO_WORK_OUTER}/e2e/data/:/data
      - ${DOJO_WORK_OUTER}/e2e/cache/:/cache
    mem_limit: 550m
